export enum PermissionModule {
  AUTH = 'auth',
  USERS = 'users',
  ROLES = 'roles',
  PERMISSIONS = 'permissions',
  MENU = 'menu',
  ORDERS = 'orders',
  INVENTORY = 'inventory',
  STAFF = 'staff',
  RESERVATIONS = 'reservations',
  REPORTS = 'reports',
  SETTINGS = 'settings',
  ITEMS = 'items',
  PURCHASES = 'purchases',
  SUPPLIERS = 'suppliers',
  SALES = 'sales',
  KOT = 'kot',
  LEDGER = 'ledger',
}
