/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as ReservationsRouteImport } from './routes/reservations'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PosRouteImport } from './routes/pos'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as KotRouteImport } from './routes/kot'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ItemsCreateRouteImport } from './routes/items_.create'
import { Route as ItemsIdRouteImport } from './routes/items_.$id'
import { Route as CategoriesTreeRouteImport } from './routes/categories_.tree'
import { Route as CategoriesCreateRouteImport } from './routes/categories_.create'
import { Route as CategoriesIdRouteImport } from './routes/categories_.$id'
import { Route as CategoriesIdEditRouteImport } from './routes/categories_.$id_.edit'

const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsRoute = ReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const KotRoute = KotRouteImport.update({
  id: '/kot',
  path: '/kot',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsCreateRoute = ItemsCreateRouteImport.update({
  id: '/items_/create',
  path: '/items/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsIdRoute = ItemsIdRouteImport.update({
  id: '/items_/$id',
  path: '/items/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesTreeRoute = CategoriesTreeRouteImport.update({
  id: '/categories_/tree',
  path: '/categories/tree',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesCreateRoute = CategoriesCreateRouteImport.update({
  id: '/categories_/create',
  path: '/categories/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIdRoute = CategoriesIdRouteImport.update({
  id: '/categories_/$id',
  path: '/categories/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIdEditRoute = CategoriesIdEditRouteImport.update({
  id: '/categories_/$id_/edit',
  path: '/categories/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/items': typeof ItemsRoute
  '/kot': typeof KotRoute
  '/ledger': typeof LedgerRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRoute
  '/pos': typeof PosRoute
  '/profile': typeof ProfileRoute
  '/purchases': typeof PurchasesRoute
  '/reports': typeof ReportsRoute
  '/reservations': typeof ReservationsRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/categories/$id': typeof CategoriesIdRoute
  '/categories/create': typeof CategoriesCreateRoute
  '/categories/tree': typeof CategoriesTreeRoute
  '/items/$id': typeof ItemsIdRoute
  '/items/create': typeof ItemsCreateRoute
  '/categories/$id/edit': typeof CategoriesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/items': typeof ItemsRoute
  '/kot': typeof KotRoute
  '/ledger': typeof LedgerRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRoute
  '/pos': typeof PosRoute
  '/profile': typeof ProfileRoute
  '/purchases': typeof PurchasesRoute
  '/reports': typeof ReportsRoute
  '/reservations': typeof ReservationsRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/categories/$id': typeof CategoriesIdRoute
  '/categories/create': typeof CategoriesCreateRoute
  '/categories/tree': typeof CategoriesTreeRoute
  '/items/$id': typeof ItemsIdRoute
  '/items/create': typeof ItemsCreateRoute
  '/categories/$id/edit': typeof CategoriesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/items': typeof ItemsRoute
  '/kot': typeof KotRoute
  '/ledger': typeof LedgerRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRoute
  '/pos': typeof PosRoute
  '/profile': typeof ProfileRoute
  '/purchases': typeof PurchasesRoute
  '/reports': typeof ReportsRoute
  '/reservations': typeof ReservationsRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/categories_/$id': typeof CategoriesIdRoute
  '/categories_/create': typeof CategoriesCreateRoute
  '/categories_/tree': typeof CategoriesTreeRoute
  '/items_/$id': typeof ItemsIdRoute
  '/items_/create': typeof ItemsCreateRoute
  '/categories_/$id_/edit': typeof CategoriesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categories'
    | '/dashboard'
    | '/inventory'
    | '/items'
    | '/kot'
    | '/ledger'
    | '/login'
    | '/menu'
    | '/orders'
    | '/pos'
    | '/profile'
    | '/purchases'
    | '/reports'
    | '/reservations'
    | '/sales'
    | '/settings'
    | '/staff'
    | '/categories/$id'
    | '/categories/create'
    | '/categories/tree'
    | '/items/$id'
    | '/items/create'
    | '/categories/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories'
    | '/dashboard'
    | '/inventory'
    | '/items'
    | '/kot'
    | '/ledger'
    | '/login'
    | '/menu'
    | '/orders'
    | '/pos'
    | '/profile'
    | '/purchases'
    | '/reports'
    | '/reservations'
    | '/sales'
    | '/settings'
    | '/staff'
    | '/categories/$id'
    | '/categories/create'
    | '/categories/tree'
    | '/items/$id'
    | '/items/create'
    | '/categories/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/categories'
    | '/dashboard'
    | '/inventory'
    | '/items'
    | '/kot'
    | '/ledger'
    | '/login'
    | '/menu'
    | '/orders'
    | '/pos'
    | '/profile'
    | '/purchases'
    | '/reports'
    | '/reservations'
    | '/sales'
    | '/settings'
    | '/staff'
    | '/categories_/$id'
    | '/categories_/create'
    | '/categories_/tree'
    | '/items_/$id'
    | '/items_/create'
    | '/categories_/$id_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriesRoute: typeof CategoriesRoute
  DashboardRoute: typeof DashboardRoute
  InventoryRoute: typeof InventoryRoute
  ItemsRoute: typeof ItemsRoute
  KotRoute: typeof KotRoute
  LedgerRoute: typeof LedgerRoute
  LoginRoute: typeof LoginRoute
  MenuRoute: typeof MenuRoute
  OrdersRoute: typeof OrdersRoute
  PosRoute: typeof PosRoute
  ProfileRoute: typeof ProfileRoute
  PurchasesRoute: typeof PurchasesRoute
  ReportsRoute: typeof ReportsRoute
  ReservationsRoute: typeof ReservationsRoute
  SalesRoute: typeof SalesRoute
  SettingsRoute: typeof SettingsRoute
  StaffRoute: typeof StaffRoute
  CategoriesIdRoute: typeof CategoriesIdRoute
  CategoriesCreateRoute: typeof CategoriesCreateRoute
  CategoriesTreeRoute: typeof CategoriesTreeRoute
  ItemsIdRoute: typeof ItemsIdRoute
  ItemsCreateRoute: typeof ItemsCreateRoute
  CategoriesIdEditRoute: typeof CategoriesIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations': {
      id: '/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof ReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kot': {
      id: '/kot'
      path: '/kot'
      fullPath: '/kot'
      preLoaderRoute: typeof KotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items_/create': {
      id: '/items_/create'
      path: '/items/create'
      fullPath: '/items/create'
      preLoaderRoute: typeof ItemsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items_/$id': {
      id: '/items_/$id'
      path: '/items/$id'
      fullPath: '/items/$id'
      preLoaderRoute: typeof ItemsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories_/tree': {
      id: '/categories_/tree'
      path: '/categories/tree'
      fullPath: '/categories/tree'
      preLoaderRoute: typeof CategoriesTreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories_/create': {
      id: '/categories_/create'
      path: '/categories/create'
      fullPath: '/categories/create'
      preLoaderRoute: typeof CategoriesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories_/$id': {
      id: '/categories_/$id'
      path: '/categories/$id'
      fullPath: '/categories/$id'
      preLoaderRoute: typeof CategoriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories_/$id_/edit': {
      id: '/categories_/$id_/edit'
      path: '/categories/$id/edit'
      fullPath: '/categories/$id/edit'
      preLoaderRoute: typeof CategoriesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesRoute: CategoriesRoute,
  DashboardRoute: DashboardRoute,
  InventoryRoute: InventoryRoute,
  ItemsRoute: ItemsRoute,
  KotRoute: KotRoute,
  LedgerRoute: LedgerRoute,
  LoginRoute: LoginRoute,
  MenuRoute: MenuRoute,
  OrdersRoute: OrdersRoute,
  PosRoute: PosRoute,
  ProfileRoute: ProfileRoute,
  PurchasesRoute: PurchasesRoute,
  ReportsRoute: ReportsRoute,
  ReservationsRoute: ReservationsRoute,
  SalesRoute: SalesRoute,
  SettingsRoute: SettingsRoute,
  StaffRoute: StaffRoute,
  CategoriesIdRoute: CategoriesIdRoute,
  CategoriesCreateRoute: CategoriesCreateRoute,
  CategoriesTreeRoute: CategoriesTreeRoute,
  ItemsIdRoute: ItemsIdRoute,
  ItemsCreateRoute: ItemsCreateRoute,
  CategoriesIdEditRoute: CategoriesIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
