import { Users, TrendingUp, Heart, UserPlus, UsersRound, Target, Coffee, UserCheck } from 'lucide-react'
import type { ReportConfig } from '../types/report-config.types'

export const customerReports: ReportConfig[] = [
  {
    id: 'customer-directory',
    title: 'Customer Directory & Segmentation',
    description: 'Complete customer database with spend and activity',
    icon: Users,
    iconBg: 'bg-blue-600',
    category: 'customer',
    categoryLabel: 'Customer Analytics',
    endpoint: '/reports/customer/directory',
    kpis: [
      { label: 'Total Customers', dataKey: 'totalCustomers', format: 'number', color: 'blue', icon: Users },
      { label: 'Active Customers', dataKey: 'activeCustomers', format: 'number', color: 'emerald', icon: UserPlus },
      { label: 'Avg Spend', dataKey: 'avgSpend', format: 'currency', color: 'purple', icon: TrendingUp },
    ],
    columns: [
      { header: 'Customer Name', accessorKey: 'customerName' },
      { header: 'Phone', accessorKey: 'phone' },
      { header: 'Type', accessorKey: 'customerType' },
      { header: 'Total Visits', accessorKey: 'totalVisits', align: 'right' },
      { header: 'Total Spend', accessorKey: 'totalSpend', align: 'right', format: 'currency' },
      { header: 'Avg Order Value', accessorKey: 'avgOrderValue', align: 'right', format: 'currency' },
      { header: 'Last Visit', accessorKey: 'lastVisit', format: 'date' },
    ],
    searchable: true,
    searchFields: ['customerName', 'phone', 'customerType'],
  },
  {
    id: 'customer-revenue',
    title: 'Customer Revenue Analysis',
    description: 'Top customers and revenue concentration',
    icon: TrendingUp,
    iconBg: 'bg-emerald-600',
    category: 'customer',
    categoryLabel: 'Customer Analytics',
    endpoint: '/reports/customer/revenue',
    kpis: [
      { label: 'Top Customer Revenue', dataKey: 'topCustomerRevenue', format: 'currency', color: 'emerald', icon: TrendingUp },
      { label: 'Top 10% Share', dataKey: 'top10PercentShare', format: 'percent', color: 'purple', icon: Users },
    ],
    columns: [
      { header: 'Customer', accessorKey: 'customerName' },
      { header: 'Total Revenue', accessorKey: 'totalRevenue', align: 'right', format: 'currency' },
      { header: '% of Total', accessorKey: 'revenueShare', align: 'right', format: 'percent' },
      { header: 'Orders', accessorKey: 'orderCount', align: 'right' },
    ],
    searchable: true,
    searchFields: ['customerName'],
  },
  {
    id: 'customer-loyalty',
    title: 'Customer Loyalty & Retention',
    description: 'RFM analysis, retention rate, and churn risk',
    icon: Heart,
    iconBg: 'bg-rose-600',
    category: 'customer',
    categoryLabel: 'Customer Analytics',
    endpoint: '/reports/customer/loyalty',
    kpis: [
      { label: 'Repeat Rate', dataKey: 'repeatRate', format: 'percent', color: 'rose', icon: Heart },
      { label: 'Churn Risk', dataKey: 'churnRisk', format: 'number', color: 'red', icon: Users },
      { label: 'Avg Tenure', dataKey: 'avgTenureDays', color: 'blue', icon: Users },
    ],
    columns: [
      { header: 'Customer', accessorKey: 'customerName' },
      { header: 'First Visit', accessorKey: 'firstVisit', format: 'date' },
      { header: 'Last Visit', accessorKey: 'lastVisit', format: 'date' },
      { header: 'Visits', accessorKey: 'totalVisits', align: 'right' },
      { header: 'RFM Score', accessorKey: 'rfmScore', align: 'right' },
    ],
    searchable: true,
    searchFields: ['customerName'],
  },
  {
    id: 'customer-new-vs-returning',
    title: 'New vs Returning Customers',
    description: 'Customer acquisition and retention balance',
    icon: UserPlus,
    iconBg: 'bg-indigo-600',
    category: 'customer',
    categoryLabel: 'Customer Analytics',
    endpoint: '/reports/customer/new-vs-returning',
    kpis: [
      { label: 'New Customers', dataKey: 'newCustomers', format: 'number', color: 'emerald', icon: UserPlus },
      { label: 'Returning Customers', dataKey: 'returningCustomers', format: 'number', color: 'blue', icon: Users },
      { label: 'Retention Rate', dataKey: 'retentionRate', format: 'percent', color: 'purple', icon: Heart },
    ],
    columns: [
      { header: 'Period', accessorKey: 'period' },
      { header: 'New', accessorKey: 'newCustomers', align: 'right' },
      { header: 'Returning', accessorKey: 'returningCustomers', align: 'right' },
      { header: 'New Revenue', accessorKey: 'newRevenue', align: 'right', format: 'currency' },
      { header: 'Returning Revenue', accessorKey: 'returningRevenue', align: 'right', format: 'currency' },
    ],
  },
  {
    id: 'customer-type-analysis',
    title: 'Customer Type Analysis',
    description: 'Revenue and behavior by customer segment',
    icon: UsersRound,
    iconBg: 'bg-teal-600',
    category: 'customer',
    categoryLabel: 'Customer Analytics',
    endpoint: '/reports/customer/type-analysis',
    kpis: [
      { label: 'Segments', dataKey: 'segmentCount', format: 'number', color: 'teal', icon: UsersRound },
      { label: 'Avg AOV by Type', dataKey: 'avgAov', format: 'currency', color: 'blue', icon: TrendingUp },
    ],
    columns: [
      { header: 'Customer Type', accessorKey: 'customerType' },
      { header: 'Customer Count', accessorKey: 'customerCount', align: 'right' },
      { header: 'Total Revenue', accessorKey: 'totalRevenue', align: 'right', format: 'currency' },
      { header: 'Avg Order Value', accessorKey: 'avgOrderValue', align: 'right', format: 'currency' },
    ],
  },
  {
    id: 'customer-lifetime-value',
    title: 'Customer Lifetime Value',
    description: 'CLV analysis and customer value segmentation',
    icon: Target,
    iconBg: 'bg-amber-600',
    category: 'customer',
    categoryLabel: 'Customer Analytics',
    endpoint: '/reports/customer/lifetime-value',
    kpis: [
      { label: 'Avg CLV', dataKey: 'avgClv', format: 'currency', color: 'amber', icon: Target },
      { label: 'High Value', dataKey: 'highValueCount', format: 'number', color: 'emerald', icon: TrendingUp },
    ],
    columns: [
      { header: 'Customer', accessorKey: 'customerName' },
      { header: 'Tenure (Months)', accessorKey: 'tenureMonths', align: 'right' },
      { header: 'Total Spend', accessorKey: 'totalSpend', align: 'right', format: 'currency' },
      { header: 'Monthly Avg', accessorKey: 'monthlyAvg', align: 'right', format: 'currency' },
      { header: 'Projected Annual', accessorKey: 'projectedAnnual', align: 'right', format: 'currency' },
    ],
    searchable: true,
    searchFields: ['customerName'],
  },
  {
    id: 'customer-preferences',
    title: 'Customer Order Preferences',
    description: 'Favorite items, categories, and ordering patterns',
    icon: Coffee,
    iconBg: 'bg-orange-600',
    category: 'customer',
    categoryLabel: 'Customer Analytics',
    endpoint: '/reports/customer/preferences',
    kpis: [
      { label: 'Top Item Orders', dataKey: 'topItemOrders', format: 'number', color: 'orange', icon: Coffee },
      { label: 'Avg Items/Order', dataKey: 'avgItemsPerOrder', format: 'decimal', color: 'purple', icon: Users },
    ],
    columns: [
      { header: 'Customer', accessorKey: 'customerName' },
      { header: 'Favorite Item', accessorKey: 'favoriteItem' },
      { header: 'Preferred Category', accessorKey: 'preferredCategory' },
      { header: 'Avg Items/Order', accessorKey: 'avgItemsPerOrder', align: 'right', format: 'decimal' },
      { header: 'Preferred Time', accessorKey: 'preferredTime' },
    ],
    searchable: true,
    searchFields: ['customerName', 'favoriteItem', 'preferredCategory'],
  },
  {
    id: 'customer-walkin-vs-registered',
    title: 'Walk-in vs Registered Customers',
    description: 'Revenue comparison between walk-in and registered guests',
    icon: UserCheck,
    iconBg: 'bg-cyan-600',
    category: 'customer',
    categoryLabel: 'Customer Analytics',
    endpoint: '/reports/customer/walkin-vs-registered',
    kpis: [
      { label: 'Walk-in Revenue', dataKey: 'walkinRevenue', format: 'currency', color: 'cyan', icon: Users },
      { label: 'Registered Revenue', dataKey: 'registeredRevenue', format: 'currency', color: 'blue', icon: UserCheck },
    ],
    columns: [
      { header: 'Segment', accessorKey: 'segment' },
      { header: 'Invoices', accessorKey: 'invoiceCount', align: 'right' },
      { header: 'Total Revenue', accessorKey: 'totalRevenue', align: 'right', format: 'currency' },
      { header: 'Avg Order Value', accessorKey: 'avgOrderValue', align: 'right', format: 'currency' },
    ],
  },
]
