import { LayoutDashboard, BarChart3, HeartPulse, TrendingUp, GitCompare } from 'lucide-react'
import type { ReportConfig } from '../types/report-config.types'

export const executiveReports: ReportConfig[] = [
  {
    id: 'executive-kpi-dashboard',
    title: 'Executive KPI Dashboard',
    description: 'Top-level business metrics — revenue, profit, operations, customers',
    icon: LayoutDashboard,
    iconBg: 'bg-gray-900',
    category: 'executive',
    categoryLabel: 'Executive Dashboard',
    endpoint: '/reports/executive/kpi-dashboard',
    kpis: [
      { label: 'Total Revenue', dataKey: 'totalRevenue', format: 'currency', color: 'emerald', icon: TrendingUp },
      { label: 'Gross Margin', dataKey: 'grossMargin', format: 'percent', color: 'blue', icon: BarChart3 },
      { label: 'Net Profit', dataKey: 'netProfit', format: 'currency', color: 'emerald', icon: LayoutDashboard },
      { label: 'Repeat Rate', dataKey: 'repeatRate', format: 'percent', color: 'purple', icon: HeartPulse },
      { label: 'Table Turnover', dataKey: 'tableTurnover', format: 'decimal', color: 'indigo', icon: BarChart3 },
      { label: 'Waste %', dataKey: 'wastePercent', format: 'percent', color: 'red', icon: HeartPulse },
    ],
    noTable: true,
  },
  {
    id: 'executive-profitability',
    title: 'Profitability Analysis by Dimension',
    description: 'Drill into profit by category, item, zone, and time',
    icon: BarChart3,
    iconBg: 'bg-blue-600',
    category: 'executive',
    categoryLabel: 'Executive Dashboard',
    endpoint: '/reports/executive/profitability',
    kpis: [
      { label: 'Gross Profit', dataKey: 'grossProfit', format: 'currency', color: 'emerald', icon: TrendingUp },
      { label: 'Avg Margin', dataKey: 'avgMargin', format: 'percent', color: 'blue', icon: BarChart3 },
    ],
    columns: [
      { header: 'Dimension', accessorKey: 'dimension' },
      { header: 'Revenue', accessorKey: 'revenue', align: 'right', format: 'currency' },
      { header: 'Cost', accessorKey: 'cost', align: 'right', format: 'currency' },
      { header: 'Profit', accessorKey: 'profit', align: 'right', format: 'currency' },
      { header: 'Margin %', accessorKey: 'margin', align: 'right', format: 'percent' },
    ],
    searchable: true,
    searchFields: ['dimension'],
  },
  {
    id: 'executive-health-scorecard',
    title: 'Business Health Scorecard',
    description: 'Weighted score across financial, operational, customer, and compliance health',
    icon: HeartPulse,
    iconBg: 'bg-rose-600',
    category: 'executive',
    categoryLabel: 'Executive Dashboard',
    endpoint: '/reports/executive/health-scorecard',
    kpis: [
      { label: 'Overall Score', dataKey: 'overallScore', format: 'number', color: 'rose', icon: HeartPulse },
      { label: 'Financial', dataKey: 'financialScore', format: 'number', color: 'blue', icon: BarChart3 },
      { label: 'Operational', dataKey: 'operationalScore', format: 'number', color: 'emerald', icon: TrendingUp },
      { label: 'Customer', dataKey: 'customerScore', format: 'number', color: 'purple', icon: HeartPulse },
    ],
    columns: [
      { header: 'Category', accessorKey: 'category' },
      { header: 'Score', accessorKey: 'score', align: 'right' },
      { header: 'Weight', accessorKey: 'weight', align: 'right', format: 'percent' },
      { header: 'Status', accessorKey: 'status' },
    ],
  },
  {
    id: 'executive-trend-forecast',
    title: 'Trend Analysis & Forecasting',
    description: '12-month historical trends with 3-month projections',
    icon: TrendingUp,
    iconBg: 'bg-indigo-600',
    category: 'executive',
    categoryLabel: 'Executive Dashboard',
    endpoint: '/reports/executive/trend-forecast',
    kpis: [
      { label: 'Revenue Trend', dataKey: 'revenueGrowth', format: 'percent', color: 'emerald', icon: TrendingUp },
      { label: 'Forecast Next Month', dataKey: 'forecastNextMonth', format: 'currency', color: 'blue', icon: BarChart3 },
    ],
    columns: [
      { header: 'Period', accessorKey: 'period' },
      { header: 'Revenue', accessorKey: 'revenue', align: 'right', format: 'currency' },
      { header: 'Orders', accessorKey: 'orders', align: 'right' },
      { header: 'AOV', accessorKey: 'avgOrderValue', align: 'right', format: 'currency' },
      { header: 'Food Cost %', accessorKey: 'foodCostPercent', align: 'right', format: 'percent' },
      { header: 'Type', accessorKey: 'type' },
    ],
  },
  {
    id: 'executive-comparative',
    title: 'Comparative Analysis Report',
    description: 'Side-by-side comparison across periods, categories, and zones',
    icon: GitCompare,
    iconBg: 'bg-cyan-600',
    category: 'executive',
    categoryLabel: 'Executive Dashboard',
    endpoint: '/reports/executive/comparative',
    kpis: [
      { label: 'Period Revenue', dataKey: 'periodRevenue', format: 'currency', color: 'cyan', icon: GitCompare },
      { label: 'Period vs Period', dataKey: 'periodChange', format: 'percent', color: 'emerald', icon: TrendingUp },
    ],
    columns: [
      { header: 'Dimension', accessorKey: 'dimension' },
      { header: 'Current', accessorKey: 'current', align: 'right', format: 'currency' },
      { header: 'Previous', accessorKey: 'previous', align: 'right', format: 'currency' },
      { header: 'Change', accessorKey: 'change', align: 'right', format: 'percent' },
      { header: 'Direction', accessorKey: 'direction' },
    ],
  },
]
