import { BarChart3, TrendingUp, Wallet, FileText, Receipt, IndianRupee, ScrollText, BookOpen } from 'lucide-react'
import type { ReportConfig } from '../types/report-config.types'

export const financialReports: ReportConfig[] = [
  {
    id: 'finance-balance-sheet',
    title: 'Balance Sheet',
    description: 'Account balances and financial position',
    icon: BarChart3,
    iconBg: 'bg-cyan-600',
    category: 'financial',
    categoryLabel: 'Financial & Accounting',
    endpoint: '/reports/finance/balance-sheet',
    kpis: [
      { label: 'Total Credits', dataKey: 'totalCredits', format: 'currency', color: 'emerald', icon: IndianRupee },
      { label: 'Total Debits', dataKey: 'totalDebits', format: 'currency', color: 'red', icon: IndianRupee },
      { label: 'Net Balance', dataKey: 'netBalance', format: 'currency', color: 'blue', icon: BarChart3 },
      { label: 'Accounts', dataKey: 'accounts.length', format: 'number', color: 'purple', icon: BookOpen },
    ],
    columns: [
      { header: 'Account Name', accessorKey: 'name' },
      { header: 'Opening Balance', accessorKey: 'openingBalance', align: 'right', format: 'currency' },
      { header: 'Total Credits', accessorKey: 'totalCredits', align: 'right', format: 'currency' },
      { header: 'Total Debits', accessorKey: 'totalDebits', align: 'right', format: 'currency' },
      { header: 'Current Balance', accessorKey: 'currentBalance', align: 'right', format: 'currency' },
    ],
  },
  {
    id: 'finance-profit-loss',
    title: 'Profit & Loss Statement',
    description: 'Revenue, costs, and profitability analysis',
    icon: TrendingUp,
    iconBg: 'bg-emerald-600',
    category: 'financial',
    categoryLabel: 'Financial & Accounting',
    endpoint: '/reports/finance/profit-loss',
    kpis: [
      { label: 'Net Revenue', dataKey: 'revenue.netRevenue', format: 'currency', color: 'emerald', icon: TrendingUp },
      { label: 'Gross Profit', dataKey: 'grossProfit', format: 'currency', color: 'blue', icon: IndianRupee },
      { label: 'Net Profit', dataKey: 'netProfit', format: 'currency', color: 'emerald', icon: IndianRupee },
      { label: 'Net Margin', dataKey: 'netMargin', format: 'percent', color: 'purple', icon: BarChart3 },
    ],
    columns: [
      { header: 'Category', accessorKey: 'category' },
      { header: 'Amount', accessorKey: 'amount', align: 'right', format: 'currency' },
    ],
  },
  {
    id: 'finance-cash-flow',
    title: 'Cash Flow Statement',
    description: 'Cash inflows and outflows from operations',
    icon: Wallet,
    iconBg: 'bg-blue-600',
    category: 'financial',
    categoryLabel: 'Financial & Accounting',
    endpoint: '/reports/finance/cash-flow',
    kpis: [
      { label: 'Operating Cash Flow', dataKey: 'operatingCashFlow', format: 'currency', color: 'emerald', icon: Wallet },
      { label: 'Net Cash Change', dataKey: 'netChange', format: 'currency', color: 'blue', icon: TrendingUp },
    ],
    columns: [
      { header: 'Activity', accessorKey: 'activity' },
      { header: 'Category', accessorKey: 'category' },
      { header: 'Amount', accessorKey: 'amount', align: 'right', format: 'currency' },
    ],
  },
  {
    id: 'finance-gst-return',
    title: 'GST Return Report (GSTR-1/3B)',
    description: 'Tax collected, paid, and net liability',
    icon: FileText,
    iconBg: 'bg-purple-600',
    category: 'financial',
    categoryLabel: 'Financial & Accounting',
    endpoint: '/reports/finance/gst-return',
    kpis: [
      { label: 'GST Collected', dataKey: 'totalGstCollected', format: 'currency', color: 'purple', icon: FileText },
      { label: 'ITC Claimed', dataKey: 'totalItc', format: 'currency', color: 'blue', icon: Receipt },
      { label: 'Net Payable', dataKey: 'netPayable', format: 'currency', color: 'red', icon: IndianRupee },
    ],
    columns: [
      { header: 'GST Rate', accessorKey: 'rate', align: 'center' },
      { header: 'Taxable Value', accessorKey: 'taxableValue', align: 'right', format: 'currency' },
      { header: 'CGST', accessorKey: 'cgst', align: 'right', format: 'currency' },
      { header: 'SGST', accessorKey: 'sgst', align: 'right', format: 'currency' },
      { header: 'Total Tax', accessorKey: 'totalTax', align: 'right', format: 'currency' },
    ],
  },
  {
    id: 'finance-expenses',
    title: 'Expense Report',
    description: 'Operating expenses breakdown and cost control',
    icon: Receipt,
    iconBg: 'bg-rose-600',
    category: 'financial',
    categoryLabel: 'Financial & Accounting',
    endpoint: '/reports/finance/expenses',
    kpis: [
      { label: 'Total Expenses', dataKey: 'totalExpenses', format: 'currency', color: 'red', icon: Receipt },
      { label: 'Categories', dataKey: 'categoryCount', format: 'number', color: 'purple', icon: ScrollText },
    ],
    columns: [
      { header: 'Category', accessorKey: 'category' },
      { header: 'Description', accessorKey: 'description' },
      { header: 'Date', accessorKey: 'date', format: 'date' },
      { header: 'Amount', accessorKey: 'amount', align: 'right', format: 'currency' },
      { header: '% of Total', accessorKey: 'percentage', align: 'right', format: 'percent' },
    ],
    searchable: true,
    searchFields: ['category', 'description'],
  },
  {
    id: 'finance-revenue-vs-expense',
    title: 'Revenue vs Expense Comparison',
    description: 'Monthly revenue and expense trend comparison',
    icon: TrendingUp,
    iconBg: 'bg-teal-600',
    category: 'financial',
    categoryLabel: 'Financial & Accounting',
    endpoint: '/reports/finance/revenue-vs-expense',
    kpis: [
      { label: 'Total Revenue', dataKey: 'totalRevenue', format: 'currency', color: 'emerald', icon: TrendingUp },
      { label: 'Total Expenses', dataKey: 'totalExpenses', format: 'currency', color: 'red', icon: Receipt },
      { label: 'Net Income', dataKey: 'netIncome', format: 'currency', color: 'blue', icon: IndianRupee },
    ],
    columns: [
      { header: 'Period', accessorKey: 'period' },
      { header: 'Revenue', accessorKey: 'revenue', align: 'right', format: 'currency' },
      { header: 'Expenses', accessorKey: 'expenses', align: 'right', format: 'currency' },
      { header: 'Net Income', accessorKey: 'netIncome', align: 'right', format: 'currency' },
    ],
  },
  {
    id: 'finance-tax-summary',
    title: 'Tax Summary Report',
    description: 'All tax collected, paid, and net liability',
    icon: ScrollText,
    iconBg: 'bg-indigo-600',
    category: 'financial',
    categoryLabel: 'Financial & Accounting',
    endpoint: '/reports/finance/tax-summary',
    kpis: [
      { label: 'CGST Collected', dataKey: 'cgstCollected', format: 'currency', color: 'indigo', icon: ScrollText },
      { label: 'SGST Collected', dataKey: 'sgstCollected', format: 'currency', color: 'purple', icon: ScrollText },
      { label: 'Net GST Liability', dataKey: 'netGstLiability', format: 'currency', color: 'red', icon: IndianRupee },
    ],
    columns: [
      { header: 'Tax Type', accessorKey: 'taxType' },
      { header: 'Collected', accessorKey: 'collected', align: 'right', format: 'currency' },
      { header: 'Paid (ITC)', accessorKey: 'paid', align: 'right', format: 'currency' },
      { header: 'Net Liability', accessorKey: 'netLiability', align: 'right', format: 'currency' },
    ],
  },
  {
    id: 'finance-ledger-statement',
    title: 'Ledger Account Statement',
    description: 'Complete account transaction history',
    icon: BookOpen,
    iconBg: 'bg-slate-600',
    category: 'financial',
    categoryLabel: 'Financial & Accounting',
    endpoint: '/reports/finance/ledger-statement',
    kpis: [
      { label: 'Opening Balance', dataKey: 'openingBalance', format: 'currency', color: 'gray', icon: BookOpen },
      { label: 'Closing Balance', dataKey: 'closingBalance', format: 'currency', color: 'blue', icon: IndianRupee },
    ],
    columns: [
      { header: 'Date', accessorKey: 'date', format: 'date' },
      { header: 'Type', accessorKey: 'type' },
      { header: 'Description', accessorKey: 'description' },
      { header: 'Amount', accessorKey: 'amount', align: 'right', format: 'currency' },
      { header: 'Running Balance', accessorKey: 'balanceAfter', align: 'right', format: 'currency' },
    ],
    searchable: true,
    searchFields: ['description'],
  },
]
