import { Package, AlertTriangle, ClipboardList, DollarSign, Trash2, TrendingDown, ChefHat, Calculator, Scale, Truck, Clock } from 'lucide-react'
import type { ReportConfig } from '../types/report-config.types'

export const inventoryReports: ReportConfig[] = [
  {
    id: 'inventory-stock-status',
    title: 'Current Stock Status',
    description: 'All inventory items, their stock levels, and valuation',
    icon: Package,
    iconBg: 'bg-emerald-600',
    category: 'inventory',
    categoryLabel: 'Inventory & Stock',
    endpoint: '/reports/inventory/stock-status',
    kpis: [
      { label: 'Total Items', dataKey: 'summary.totalItems', format: 'number', color: 'emerald', icon: Package },
      { label: 'Total Value', dataKey: 'summary.totalValue', format: 'currency', color: 'blue', icon: DollarSign },
      { label: 'Low Stock', dataKey: 'summary.lowStockCount', format: 'number', color: 'amber', icon: AlertTriangle },
      { label: 'Out of Stock', dataKey: 'summary.outOfStockCount', format: 'number', color: 'red', icon: Trash2 },
    ],
    columns: [
      { header: 'Item', accessorKey: 'itemName' },
      { header: 'SKU', accessorKey: 'sku' },
      { header: 'Category', accessorKey: 'categoryName' },
      { header: 'Current Stock', accessorKey: 'currentStock', align: 'right', format: 'decimal' },
      { header: 'Min Level', accessorKey: 'minStockLevel', align: 'right', format: 'decimal' },
      { header: 'Unit Cost', accessorKey: 'unitCost', align: 'right', format: 'currency' },
      { header: 'Stock Value', accessorKey: 'stockValue', align: 'right', format: 'currency' },
    ],
    searchable: true,
    searchFields: ['itemName', 'sku', 'categoryName'],
  },
  {
    id: 'inventory-low-stock',
    title: 'Low Stock Alerts',
    description: 'Items that need immediate restocking',
    icon: AlertTriangle,
    iconBg: 'bg-red-600',
    category: 'inventory',
    categoryLabel: 'Inventory & Stock',
    endpoint: '/reports/inventory/low-stock',
    kpis: [
      { label: 'Total Alerts', dataKey: 'totalAlerts', format: 'number', color: 'red', icon: AlertTriangle },
      { label: 'Out of Stock', dataKey: 'outOfStock', format: 'number', color: 'red', icon: Trash2 },
      { label: 'Low Stock', dataKey: 'lowStock', format: 'number', color: 'amber', icon: AlertTriangle },
    ],
    columns: [
      { header: 'Item', accessorKey: 'itemName' },
      { header: 'SKU', accessorKey: 'sku' },
      { header: 'Current Stock', accessorKey: 'currentStock', align: 'right', format: 'decimal' },
      { header: 'Min Level', accessorKey: 'minStockLevel', align: 'right', format: 'decimal' },
      { header: 'Deficit', accessorKey: 'deficit', align: 'right', format: 'decimal' },
    ],
    searchable: true,
    searchFields: ['itemName', 'sku'],
  },
  {
    id: 'inventory-movements',
    title: 'Stock Movement Ledger',
    description: 'Complete audit trail of all inventory transactions',
    icon: ClipboardList,
    iconBg: 'bg-indigo-600',
    category: 'inventory',
    categoryLabel: 'Inventory & Stock',
    endpoint: '/reports/inventory/movements',
    kpis: [
      { label: 'Total Movements', dataKey: 'totalMovements', format: 'number', color: 'indigo', icon: ClipboardList },
      { label: 'Items Affected', dataKey: 'uniqueItems', format: 'number', color: 'blue', icon: Package },
    ],
    columns: [
      { header: 'Date', accessorKey: 'date', format: 'date' },
      { header: 'Item', accessorKey: 'itemName' },
      { header: 'Type', accessorKey: 'movementType' },
      { header: 'Quantity', accessorKey: 'quantity', align: 'right', format: 'decimal' },
      { header: 'Balance Before', accessorKey: 'balanceBefore', align: 'right', format: 'decimal' },
      { header: 'Balance After', accessorKey: 'balanceAfter', align: 'right', format: 'decimal' },
      { header: 'Reference', accessorKey: 'reference' },
      { header: 'Notes', accessorKey: 'notes' },
    ],
    searchable: true,
    searchFields: ['itemName', 'movementType', 'reference', 'notes'],
  },
  {
    id: 'inventory-valuation',
    title: 'Stock Valuation Report',
    description: 'Monetary value of current inventory by category',
    icon: DollarSign,
    iconBg: 'bg-green-600',
    category: 'inventory',
    categoryLabel: 'Inventory & Stock',
    endpoint: '/reports/inventory/valuation',
    kpis: [
      { label: 'Total Inventory Value', dataKey: 'totalValue', format: 'currency', color: 'emerald', icon: DollarSign },
      { label: 'Categories', dataKey: 'categoryCount', format: 'number', color: 'blue', icon: Scale },
    ],
    columns: [
      { header: 'Item', accessorKey: 'itemName' },
      { header: 'Category', accessorKey: 'categoryName' },
      { header: 'Product Type', accessorKey: 'productType' },
      { header: 'Current Stock', accessorKey: 'currentStock', align: 'right', format: 'decimal' },
      { header: 'Unit Cost', accessorKey: 'unitCost', align: 'right', format: 'currency' },
      { header: 'Stock Value', accessorKey: 'stockValue', align: 'right', format: 'currency' },
    ],
    searchable: true,
    searchFields: ['itemName', 'categoryName'],
  },
  {
    id: 'inventory-wastage',
    title: 'Wastage Report',
    description: 'Food waste tracking and loss analysis',
    icon: Trash2,
    iconBg: 'bg-orange-600',
    category: 'inventory',
    categoryLabel: 'Inventory & Stock',
    endpoint: '/reports/inventory/wastage',
    kpis: [
      { label: 'Total Wastage', dataKey: 'totalWastage', format: 'currency', color: 'red', icon: Trash2 },
      { label: 'Wastage Rate', dataKey: 'wastageRate', format: 'percent', color: 'amber', icon: TrendingDown },
    ],
    columns: [
      { header: 'Item', accessorKey: 'itemName' },
      { header: 'Wastage Qty', accessorKey: 'wastageQuantity', align: 'right', format: 'decimal' },
      { header: 'Wastage Value', accessorKey: 'wastageValue', align: 'right', format: 'currency' },
      { header: 'Reason', accessorKey: 'reason' },
    ],
    searchable: true,
    searchFields: ['itemName', 'reason'],
  },
  {
    id: 'inventory-consumption',
    title: 'Consumption Analysis',
    description: 'Daily consumption patterns and stockout projections',
    icon: TrendingDown,
    iconBg: 'bg-purple-600',
    category: 'inventory',
    categoryLabel: 'Inventory & Stock',
    endpoint: '/reports/inventory/consumption',
    kpis: [
      { label: 'Total Consumed', dataKey: 'totalConsumed', format: 'decimal', color: 'purple', icon: TrendingDown },
      { label: 'Avg Daily', dataKey: 'avgDailyConsumption', format: 'decimal', color: 'blue', icon: Package },
    ],
    columns: [
      { header: 'Item', accessorKey: 'itemName' },
      { header: 'Total Consumed', accessorKey: 'totalConsumed', align: 'right', format: 'decimal' },
      { header: 'Avg Daily', accessorKey: 'avgDaily', align: 'right', format: 'decimal' },
      { header: 'Stockout In', accessorKey: 'daysUntilStockout', align: 'right' },
    ],
    searchable: true,
    searchFields: ['itemName'],
  },
  {
    id: 'inventory-production',
    title: 'Production Report',
    description: 'Batch production tracking and ingredient usage',
    icon: ChefHat,
    iconBg: 'bg-amber-600',
    category: 'inventory',
    categoryLabel: 'Inventory & Stock',
    endpoint: '/reports/inventory/production',
    kpis: [
      { label: 'Total Batches', dataKey: 'totalBatches', format: 'number', color: 'amber', icon: ChefHat },
      { label: 'Total Cost', dataKey: 'totalCost', format: 'currency', color: 'red', icon: Calculator },
    ],
    columns: [
      { header: 'Date', accessorKey: 'date', format: 'date' },
      { header: 'Output Item', accessorKey: 'itemName' },
      { header: 'Batch Qty', accessorKey: 'batchQuantity', align: 'right', format: 'decimal' },
      { header: 'Production Cost', accessorKey: 'productionCost', align: 'right', format: 'currency' },
      { header: 'Created By', accessorKey: 'createdBy' },
    ],
    searchable: true,
    searchFields: ['itemName', 'createdBy'],
  },
  {
    id: 'inventory-recipe-costs',
    title: 'Recipe Cost Analysis',
    description: 'Menu item profitability and food cost percentages',
    icon: Calculator,
    iconBg: 'bg-cyan-600',
    category: 'inventory',
    categoryLabel: 'Inventory & Stock',
    endpoint: '/reports/inventory/recipe-costs',
    kpis: [
      { label: 'Items Analyzed', dataKey: 'totalItems', format: 'number', color: 'cyan', icon: Calculator },
      { label: 'Avg Food Cost', dataKey: 'avgFoodCost', format: 'percent', color: 'amber', icon: TrendingDown },
    ],
    columns: [
      { header: 'Item', accessorKey: 'itemName' },
      { header: 'Ingredient Cost', accessorKey: 'totalIngredientCost', align: 'right', format: 'currency' },
      { header: 'Cost per Unit', accessorKey: 'costPerUnit', align: 'right', format: 'currency' },
      { header: 'Selling Price', accessorKey: 'sellingPrice', align: 'right', format: 'currency' },
      { header: 'Food Cost %', accessorKey: 'foodCostPercent', align: 'right', format: 'percent' },
      { header: 'Gross Margin', accessorKey: 'grossMargin', align: 'right', format: 'currency' },
    ],
    searchable: true,
    searchFields: ['itemName'],
  },
  {
    id: 'inventory-reconciliation',
    title: 'Stock Reconciliation',
    description: 'Physical vs system stock comparison',
    icon: Scale,
    iconBg: 'bg-teal-600',
    category: 'inventory',
    categoryLabel: 'Inventory & Stock',
    endpoint: '/reports/inventory/reconciliation',
    kpis: [
      { label: 'Items Checked', dataKey: 'totalItems', format: 'number', color: 'teal', icon: Scale },
      { label: 'Items with Variance', dataKey: 'itemsWithVariance', format: 'number', color: 'red', icon: AlertTriangle },
    ],
    columns: [
      { header: 'Item', accessorKey: 'itemName' },
      { header: 'System Stock', accessorKey: 'systemStock', align: 'right', format: 'decimal' },
      { header: 'Physical Count', accessorKey: 'physicalCount', align: 'right', format: 'decimal' },
      { header: 'Variance', accessorKey: 'variance', align: 'right', format: 'decimal' },
      { header: 'Variance Value', accessorKey: 'varianceValue', align: 'right', format: 'currency' },
    ],
    searchable: true,
    searchFields: ['itemName'],
  },
  {
    id: 'inventory-purchase-timeline',
    title: 'Purchase-to-Stock Timeline',
    description: 'Supplier lead time and delivery performance',
    icon: Truck,
    iconBg: 'bg-sky-600',
    category: 'inventory',
    categoryLabel: 'Inventory & Stock',
    endpoint: '/reports/inventory/purchase-timeline',
    kpis: [
      { label: 'Total Orders', dataKey: 'totalOrders', format: 'number', color: 'sky', icon: Truck },
      { label: 'Avg Lead Time', dataKey: 'avgLeadTime', format: 'decimal', color: 'blue', icon: Clock },
    ],
    columns: [
      { header: 'PO Number', accessorKey: 'purchaseNumber' },
      { header: 'Order Date', accessorKey: 'orderDate', format: 'date' },
      { header: 'Supplier', accessorKey: 'supplierName' },
      { header: 'Received Date', accessorKey: 'receivedDate', format: 'date' },
      { header: 'Lead Time (Days)', accessorKey: 'leadTime', align: 'right' },
    ],
    searchable: true,
    searchFields: ['purchaseNumber', 'supplierName'],
  },
]
