import { CookingPot, Timer, LayoutGrid, UtensilsCrossed, XCircle, Gauge, LeafyGreen } from 'lucide-react'
import type { ReportConfig } from '../types/report-config.types'

export const kitchenReports: ReportConfig[] = [
  {
    id: 'kitchen-queue-status',
    title: 'Kitchen Order Queue Status',
    description: 'Real-time order tracking by station and status',
    icon: CookingPot,
    iconBg: 'bg-orange-600',
    category: 'kitchen',
    categoryLabel: 'Kitchen Operations',
    endpoint: '/reports/kitchen/queue-status',
    kpis: [
      { label: 'Pending', dataKey: 'pending', format: 'number', color: 'amber', icon: Timer },
      { label: 'Preparing', dataKey: 'preparing', format: 'number', color: 'blue', icon: CookingPot },
      { label: 'Ready', dataKey: 'ready', format: 'number', color: 'emerald', icon: UtensilsCrossed },
      { label: 'Overdue', dataKey: 'overdue', format: 'number', color: 'red', icon: XCircle },
    ],
    columns: [
      { header: 'KOT #', accessorKey: 'kotNumber' },
      { header: 'Station', accessorKey: 'station' },
      { header: 'Tables', accessorKey: 'tables' },
      { header: 'Items', accessorKey: 'itemCount', align: 'right' },
      { header: 'Status', accessorKey: 'status' },
      { header: 'Elapsed (min)', accessorKey: 'elapsedMinutes', align: 'right' },
    ],
    searchable: true,
    searchFields: ['kotNumber', 'station', 'tables'],
  },
  {
    id: 'kitchen-performance',
    title: 'Kitchen Performance Metrics',
    description: 'Prep times, cook times, and station efficiency',
    icon: Timer,
    iconBg: 'bg-blue-600',
    category: 'kitchen',
    categoryLabel: 'Kitchen Operations',
    endpoint: '/reports/kitchen/performance',
    kpis: [
      { label: 'Avg Prep Time', dataKey: 'avgPrepTime', format: 'decimal', color: 'blue', icon: Timer },
      { label: 'Avg Cook Time', dataKey: 'avgCookTime', format: 'decimal', color: 'amber', icon: CookingPot },
      { label: 'Avg Total Time', dataKey: 'avgTotalTime', format: 'decimal', color: 'purple', icon: Gauge },
    ],
    columns: [
      { header: 'Station', accessorKey: 'station' },
      { header: 'Avg Prep (min)', accessorKey: 'avgPrepTime', align: 'right', format: 'decimal' },
      { header: 'Avg Cook (min)', accessorKey: 'avgCookTime', align: 'right', format: 'decimal' },
      { header: 'Avg Total (min)', accessorKey: 'avgTotalTime', align: 'right', format: 'decimal' },
      { header: 'Order Count', accessorKey: 'orderCount', align: 'right' },
    ],
  },
  {
    id: 'kitchen-station-load',
    title: 'Station Load Distribution',
    description: 'Workload balance across kitchen stations',
    icon: LayoutGrid,
    iconBg: 'bg-violet-600',
    category: 'kitchen',
    categoryLabel: 'Kitchen Operations',
    endpoint: '/reports/kitchen/station-load',
    kpis: [
      { label: 'Total Orders', dataKey: 'totalOrders', format: 'number', color: 'violet', icon: LayoutGrid },
      { label: 'Busiest Station', dataKey: 'busiestStation', format: 'number', color: 'amber', icon: UtensilsCrossed },
    ],
    columns: [
      { header: 'Station', accessorKey: 'station' },
      { header: 'Orders', accessorKey: 'orderCount', align: 'right' },
      { header: 'Items', accessorKey: 'itemCount', align: 'right' },
      { header: 'Pending', accessorKey: 'pending', align: 'right' },
      { header: 'Utilization', accessorKey: 'utilization', align: 'right', format: 'percent' },
    ],
  },
  {
    id: 'kitchen-item-frequency',
    title: 'Menu Item Prep Frequency',
    description: 'Most ordered items for prep scheduling',
    icon: UtensilsCrossed,
    iconBg: 'bg-pink-600',
    category: 'kitchen',
    categoryLabel: 'Kitchen Operations',
    endpoint: '/reports/kitchen/item-frequency',
    kpis: [
      { label: 'Unique Items', dataKey: 'uniqueItems', format: 'number', color: 'pink', icon: UtensilsCrossed },
      { label: 'Total Ordered', dataKey: 'totalOrdered', format: 'number', color: 'purple', icon: Gauge },
    ],
    columns: [
      { header: 'Item', accessorKey: 'itemName' },
      { header: 'Times Ordered', accessorKey: 'timesOrdered', align: 'right' },
      { header: 'Total Qty', accessorKey: 'totalQuantity', align: 'right' },
      { header: 'Station', accessorKey: 'station' },
    ],
    searchable: true,
    searchFields: ['itemName', 'station'],
  },
  {
    id: 'kitchen-cancellation',
    title: 'KOT Cancellation & Void Report',
    description: 'Order cancellations and wasted prep analysis',
    icon: XCircle,
    iconBg: 'bg-red-600',
    category: 'kitchen',
    categoryLabel: 'Kitchen Operations',
    endpoint: '/reports/kitchen/cancellation',
    kpis: [
      { label: 'Cancelled KOTs', dataKey: 'cancelledCount', format: 'number', color: 'red', icon: XCircle },
      { label: 'Cancel Rate', dataKey: 'cancelRate', format: 'percent', color: 'amber', icon: Timer },
    ],
    columns: [
      { header: 'Station', accessorKey: 'station' },
      { header: 'Cancelled', accessorKey: 'cancelledCount', align: 'right' },
      { header: 'Cancel Rate', accessorKey: 'cancelRate', align: 'right', format: 'percent' },
    ],
  },
  {
    id: 'kitchen-throughput',
    title: 'Kitchen Throughput Analysis',
    description: 'Orders completed per hour and capacity planning',
    icon: Gauge,
    iconBg: 'bg-emerald-600',
    category: 'kitchen',
    categoryLabel: 'Kitchen Operations',
    endpoint: '/reports/kitchen/throughput',
    kpis: [
      { label: 'Peak Throughput', dataKey: 'peakThroughput', format: 'number', color: 'emerald', icon: Gauge },
      { label: 'Avg Throughput', dataKey: 'avgThroughput', format: 'number', color: 'blue', icon: Timer },
    ],
    columns: [
      { header: 'Period', accessorKey: 'period' },
      { header: 'Orders Completed', accessorKey: 'ordersCompleted', align: 'right' },
      { header: 'Items Prepared', accessorKey: 'itemsPrepared', align: 'right' },
      { header: 'Throughput/hr', accessorKey: 'throughputRate', align: 'right', format: 'decimal' },
    ],
  },
  {
    id: 'kitchen-dietary-mix',
    title: 'Dietary Mix Report',
    description: 'Veg vs non-veg order distribution and trends',
    icon: LeafyGreen,
    iconBg: 'bg-green-600',
    category: 'kitchen',
    categoryLabel: 'Kitchen Operations',
    endpoint: '/reports/kitchen/dietary-mix',
    kpis: [
      { label: 'Veg Items', dataKey: 'vegPercentage', format: 'percent', color: 'emerald', icon: LeafyGreen },
      { label: 'Non-Veg Items', dataKey: 'nonVegPercentage', format: 'percent', color: 'red', icon: UtensilsCrossed },
    ],
    columns: [
      { header: 'Category', accessorKey: 'category' },
      { header: 'Items Sold', accessorKey: 'itemCount', align: 'right' },
      { header: 'Percentage', accessorKey: 'percentage', align: 'right', format: 'percent' },
    ],
  },
]
