import { ClipboardCheck, Users, Clock, CalendarRange, UsersRound, Wallet, Ban, FileCheck, TrendingUp } from 'lucide-react'
import type { ReportConfig } from '../types/report-config.types'

export const operationalReports: ReportConfig[] = [
  {
    id: 'operations-daily-summary',
    title: 'Daily Operations Summary',
    description: 'Complete daily snapshot of sales, kitchen, seating, and inventory',
    icon: ClipboardCheck,
    iconBg: 'bg-blue-600',
    category: 'operations',
    categoryLabel: 'Daily Operations',
    endpoint: '/reports/operations/daily-summary',
    kpis: [
      { label: "Today's Revenue", dataKey: 'todayRevenue', format: 'currency', color: 'emerald', icon: Wallet },
      { label: 'Orders Today', dataKey: 'orderCount', format: 'number', color: 'blue', icon: ClipboardCheck },
      { label: 'Tables Occupied', dataKey: 'tablesOccupied', format: 'number', color: 'purple', icon: Users },
      { label: 'Low Stock Items', dataKey: 'lowStockItems', format: 'number', color: 'red', icon: Ban },
    ],
    noTable: true,
  },
  {
    id: 'operations-staff-activity',
    title: 'Staff Activity Report',
    description: 'Staff productivity and action logging',
    icon: Users,
    iconBg: 'bg-teal-600',
    category: 'operations',
    categoryLabel: 'Daily Operations',
    endpoint: '/reports/operations/staff-activity',
    kpis: [
      { label: 'Active Staff', dataKey: 'activeStaff', format: 'number', color: 'teal', icon: Users },
      { label: 'Total Actions', dataKey: 'totalActions', format: 'number', color: 'blue', icon: ClipboardCheck },
    ],
    columns: [
      { header: 'Staff Member', accessorKey: 'staffName' },
      { header: 'Role', accessorKey: 'role' },
      { header: 'Actions', accessorKey: 'actionCount', align: 'right' },
      { header: 'Orders Handled', accessorKey: 'ordersHandled', align: 'right' },
      { header: 'Last Active', accessorKey: 'lastActive' },
    ],
    searchable: true,
    searchFields: ['staffName', 'role'],
  },
  {
    id: 'operations-hourly',
    title: 'Hourly Operations Dashboard',
    description: 'Sales, orders, and activity by hour',
    icon: Clock,
    iconBg: 'bg-indigo-600',
    category: 'operations',
    categoryLabel: 'Daily Operations',
    endpoint: '/reports/operations/hourly',
    kpis: [
      { label: 'Peak Hour Sales', dataKey: 'peakHourSales', format: 'currency', color: 'indigo', icon: Clock },
      { label: 'Peak Hour Orders', dataKey: 'peakHourOrders', format: 'number', color: 'blue', icon: ClipboardCheck },
    ],
    columns: [
      { header: 'Hour', accessorKey: 'hour' },
      { header: 'Sales', accessorKey: 'sales', align: 'right', format: 'currency' },
      { header: 'Orders', accessorKey: 'orders', align: 'right' },
      { header: 'KOTs', accessorKey: 'kots', align: 'right' },
      { header: 'Tables Active', accessorKey: 'tablesActive', align: 'right' },
    ],
  },
  {
    id: 'operations-weekly-review',
    title: 'Weekly Operations Review',
    description: 'Day-by-day weekly performance comparison',
    icon: CalendarRange,
    iconBg: 'bg-emerald-600',
    category: 'operations',
    categoryLabel: 'Daily Operations',
    endpoint: '/reports/operations/weekly-review',
    kpis: [
      { label: 'Weekly Revenue', dataKey: 'weeklyRevenue', format: 'currency', color: 'emerald', icon: Wallet },
      { label: 'Best Day', dataKey: 'bestDay' },
      { label: 'WoW Change', dataKey: 'wowChange', format: 'percent', color: 'blue', icon: TrendingUp },
    ],
    columns: [
      { header: 'Day', accessorKey: 'day' },
      { header: 'Revenue', accessorKey: 'revenue', align: 'right', format: 'currency' },
      { header: 'Orders', accessorKey: 'orders', align: 'right' },
      { header: 'Avg Order', accessorKey: 'avgOrderValue', align: 'right', format: 'currency' },
      { header: 'Reservations', accessorKey: 'reservations', align: 'right' },
      { header: 'No-Shows', accessorKey: 'noShows', align: 'right' },
    ],
  },
  {
    id: 'operations-peak-staffing',
    title: 'Peak Hours & Staffing Analysis',
    description: 'Staff demand vs availability by hour',
    icon: UsersRound,
    iconBg: 'bg-amber-600',
    category: 'operations',
    categoryLabel: 'Daily Operations',
    endpoint: '/reports/operations/peak-staffing',
    kpis: [
      { label: 'Peak Staff Needed', dataKey: 'peakStaffNeeded', format: 'number', color: 'amber', icon: UsersRound },
      { label: 'Staffing Gap', dataKey: 'staffingGap', format: 'number', color: 'red', icon: Users },
    ],
    columns: [
      { header: 'Hour', accessorKey: 'hour' },
      { header: 'Revenue', accessorKey: 'revenue', align: 'right', format: 'currency' },
      { header: 'Orders/hr', accessorKey: 'ordersPerHour', align: 'right' },
      { header: 'Staff Needed', accessorKey: 'staffNeeded', align: 'right' },
      { header: 'Current Staff', accessorKey: 'currentStaff', align: 'right' },
      { header: 'Gap', accessorKey: 'gap', align: 'right' },
    ],
  },
  {
    id: 'operations-payment-collection',
    title: 'Payment Collection Report',
    description: 'Revenue by payment method and credit aging',
    icon: Wallet,
    iconBg: 'bg-green-600',
    category: 'operations',
    categoryLabel: 'Daily Operations',
    endpoint: '/reports/operations/payment-collection',
    kpis: [
      { label: 'Cash Collected', dataKey: 'cashCollected', format: 'currency', color: 'emerald', icon: Wallet },
      { label: 'Card + UPI', dataKey: 'cardUpiCollected', format: 'currency', color: 'blue', icon: Wallet },
      { label: 'Credit Outstanding', dataKey: 'creditOutstanding', format: 'currency', color: 'red', icon: Ban },
    ],
    columns: [
      { header: 'Method', accessorKey: 'method' },
      { header: 'Invoices', accessorKey: 'invoiceCount', align: 'right' },
      { header: 'Total', accessorKey: 'totalCollected', align: 'right', format: 'currency' },
      { header: '% Share', accessorKey: 'percentage', align: 'right', format: 'percent' },
      { header: 'Avg Transaction', accessorKey: 'avgTransaction', align: 'right', format: 'currency' },
    ],
  },
  {
    id: 'operations-cancellation-summary',
    title: 'Cancellation & Void Summary',
    description: 'Cancellations across invoices, KOTs, and reservations',
    icon: Ban,
    iconBg: 'bg-red-600',
    category: 'operations',
    categoryLabel: 'Daily Operations',
    endpoint: '/reports/operations/cancellation-summary',
    kpis: [
      { label: 'Total Cancelled', dataKey: 'totalCancelled', format: 'number', color: 'red', icon: Ban },
      { label: 'Revenue Impact', dataKey: 'revenueImpact', format: 'currency', color: 'purple', icon: Wallet },
      { label: 'Cancel Rate', dataKey: 'cancelRate', format: 'percent', color: 'amber', icon: Clock },
    ],
    columns: [
      { header: 'Category', accessorKey: 'category' },
      { header: 'Total Created', accessorKey: 'totalCreated', align: 'right' },
      { header: 'Cancelled', accessorKey: 'cancelled', align: 'right' },
      { header: 'Cancel Rate', accessorKey: 'cancelRate', align: 'right', format: 'percent' },
    ],
  },
  {
    id: 'operations-eod-reconciliation',
    title: 'End-of-Day Reconciliation',
    description: 'Cash, card, and inventory reconciliation checklist',
    icon: FileCheck,
    iconBg: 'bg-slate-600',
    category: 'operations',
    categoryLabel: 'Daily Operations',
    endpoint: '/reports/operations/eod-reconciliation',
    kpis: [
      { label: 'Total Revenue', dataKey: 'totalRevenue', format: 'currency', color: 'emerald', icon: Wallet },
      { label: 'Total Invoices', dataKey: 'totalInvoices', format: 'number', color: 'blue', icon: FileCheck },
      { label: 'Cancelled', dataKey: 'cancelledInvoices', format: 'number', color: 'red', icon: Ban },
      { label: 'Wastage', dataKey: 'wastageValue', format: 'currency', color: 'amber', icon: Clock },
    ],
    columns: [
      { header: 'Section', accessorKey: 'section' },
      { header: 'Metric', accessorKey: 'metric' },
      { header: 'Value', accessorKey: 'value', align: 'right', format: 'currency' },
    ],
  },
]
