import { ShoppingCart, Star, Layers, GitCompare, ArrowRightLeft, Bell, TrendingUp } from 'lucide-react'
import type { ReportConfig } from '../types/report-config.types'

export const procurementReports: ReportConfig[] = [
  {
    id: 'procurement-po-summary',
    title: 'Purchase Order Summary',
    description: 'All purchase orders by status and value',
    icon: ShoppingCart,
    iconBg: 'bg-blue-600',
    category: 'procurement',
    categoryLabel: 'Procurement & Suppliers',
    endpoint: '/reports/procurement/po-summary',
    kpis: [
      { label: 'Total POs', dataKey: 'totalPos', format: 'number', color: 'blue', icon: ShoppingCart },
      { label: 'Total Value', dataKey: 'totalValue', format: 'currency', color: 'emerald', icon: TrendingUp },
      { label: 'Outstanding', dataKey: 'outstanding', format: 'number', color: 'amber', icon: ArrowRightLeft },
    ],
    columns: [
      { header: 'PO #', accessorKey: 'purchaseNumber' },
      { header: 'Date', accessorKey: 'purchaseDate', format: 'date' },
      { header: 'Supplier', accessorKey: 'supplierName' },
      { header: 'Status', accessorKey: 'status' },
      { header: 'Total Amount', accessorKey: 'totalAmount', align: 'right', format: 'currency' },
    ],
    searchable: true,
    searchFields: ['purchaseNumber', 'supplierName', 'status'],
  },
  {
    id: 'procurement-supplier-performance',
    title: 'Supplier Performance Report',
    description: 'Supplier reliability, lead times, and spend',
    icon: Star,
    iconBg: 'bg-amber-600',
    category: 'procurement',
    categoryLabel: 'Procurement & Suppliers',
    endpoint: '/reports/procurement/supplier-performance',
    kpis: [
      { label: 'Active Suppliers', dataKey: 'activeSuppliers', format: 'number', color: 'amber', icon: Star },
      { label: 'Total Spend', dataKey: 'totalSpend', format: 'currency', color: 'blue', icon: ShoppingCart },
      { label: 'On-Time Delivery', dataKey: 'onTimeDelivery', format: 'percent', color: 'emerald', icon: Star },
    ],
    columns: [
      { header: 'Supplier', accessorKey: 'supplierName' },
      { header: 'Total Orders', accessorKey: 'totalOrders', align: 'right' },
      { header: 'Total Spend', accessorKey: 'totalSpend', align: 'right', format: 'currency' },
      { header: 'On-Time %', accessorKey: 'onTimeDelivery', align: 'right', format: 'percent' },
      { header: 'Avg Lead Time', accessorKey: 'avgLeadTime', align: 'right' },
    ],
    searchable: true,
    searchFields: ['supplierName'],
  },
  {
    id: 'procurement-purchase-by-item',
    title: 'Purchase by Item/Category',
    description: 'Purchase quantities and costs by menu item',
    icon: Layers,
    iconBg: 'bg-purple-600',
    category: 'procurement',
    categoryLabel: 'Procurement & Suppliers',
    endpoint: '/reports/procurement/purchase-by-item',
    kpis: [
      { label: 'Items Purchased', dataKey: 'totalItems', format: 'number', color: 'purple', icon: Layers },
      { label: 'Total Cost', dataKey: 'totalCost', format: 'currency', color: 'red', icon: ShoppingCart },
    ],
    columns: [
      { header: 'Item', accessorKey: 'itemName' },
      { header: 'Category', accessorKey: 'categoryName' },
      { header: 'Qty Purchased', accessorKey: 'quantityPurchased', align: 'right', format: 'decimal' },
      { header: 'Total Cost', accessorKey: 'totalCost', align: 'right', format: 'currency' },
      { header: 'Avg Unit Price', accessorKey: 'avgUnitPrice', align: 'right', format: 'currency' },
    ],
    searchable: true,
    searchFields: ['itemName', 'categoryName'],
  },
  {
    id: 'procurement-price-comparison',
    title: 'Supplier Price Comparison',
    description: 'Price comparison across suppliers for each item',
    icon: GitCompare,
    iconBg: 'bg-cyan-600',
    category: 'procurement',
    categoryLabel: 'Procurement & Suppliers',
    endpoint: '/reports/procurement/price-comparison',
    kpis: [
      { label: 'Items Compared', dataKey: 'totalItems', format: 'number', color: 'cyan', icon: GitCompare },
      { label: 'Best Value', dataKey: 'potentialSavings', format: 'currency', color: 'emerald', icon: TrendingUp },
    ],
    columns: [
      { header: 'Item', accessorKey: 'itemName' },
      { header: 'Supplier A', accessorKey: 'supplierAPrice', align: 'right', format: 'currency' },
      { header: 'Supplier B', accessorKey: 'supplierBPrice', align: 'right', format: 'currency' },
      { header: 'Best Value', accessorKey: 'bestValue' },
      { header: '% Difference', accessorKey: 'percentDifference', align: 'right', format: 'percent' },
    ],
    searchable: true,
    searchFields: ['itemName'],
  },
  {
    id: 'procurement-purchase-to-pay',
    title: 'Purchase-to-Pay Cycle',
    description: 'Order-to-receipt timeline tracking',
    icon: ArrowRightLeft,
    iconBg: 'bg-indigo-600',
    category: 'procurement',
    categoryLabel: 'Procurement & Suppliers',
    endpoint: '/reports/procurement/purchase-to-pay',
    kpis: [
      { label: 'Avg Days to Receive', dataKey: 'avgDaysToReceive', format: 'decimal', color: 'indigo', icon: ArrowRightLeft },
      { label: 'Pending Receipt', dataKey: 'pendingCount', format: 'number', color: 'amber', icon: ShoppingCart },
    ],
    columns: [
      { header: 'PO #', accessorKey: 'purchaseNumber' },
      { header: 'Supplier', accessorKey: 'supplierName' },
      { header: 'Order Date', accessorKey: 'orderDate', format: 'date' },
      { header: 'Status', accessorKey: 'status' },
      { header: 'Received Date', accessorKey: 'receivedDate', format: 'date' },
      { header: 'Days Taken', accessorKey: 'daysToReceive', align: 'right' },
    ],
    searchable: true,
    searchFields: ['purchaseNumber', 'supplierName', 'status'],
  },
  {
    id: 'procurement-reorder',
    title: 'Inventory Reorder Report',
    description: 'Items needing reorder with suggested quantities',
    icon: Bell,
    iconBg: 'bg-red-600',
    category: 'procurement',
    categoryLabel: 'Procurement & Suppliers',
    endpoint: '/reports/procurement/reorder',
    kpis: [
      { label: 'Items to Reorder', dataKey: 'itemsToReorder', format: 'number', color: 'red', icon: Bell },
      { label: 'Urgent Items', dataKey: 'urgentItems', format: 'number', color: 'red', icon: Bell },
    ],
    columns: [
      { header: 'Item', accessorKey: 'itemName' },
      { header: 'Current Stock', accessorKey: 'currentStock', align: 'right', format: 'decimal' },
      { header: 'Reorder Point', accessorKey: 'reorderPoint', align: 'right', format: 'decimal' },
      { header: 'Days Until Stockout', accessorKey: 'daysUntilStockout', align: 'right' },
      { header: 'Suggested Qty', accessorKey: 'suggestedQty', align: 'right', format: 'decimal' },
      { header: 'Preferred Supplier', accessorKey: 'preferredSupplier' },
    ],
    searchable: true,
    searchFields: ['itemName', 'preferredSupplier'],
  },
  {
    id: 'procurement-monthly-trend',
    title: 'Monthly Purchase Trend',
    description: 'Monthly PO value and count trends',
    icon: TrendingUp,
    iconBg: 'bg-emerald-600',
    category: 'procurement',
    categoryLabel: 'Procurement & Suppliers',
    endpoint: '/reports/procurement/monthly-trend',
    kpis: [
      { label: 'Month Total', dataKey: 'monthTotal', format: 'currency', color: 'emerald', icon: TrendingUp },
      { label: 'MoM Change', dataKey: 'momChange', format: 'percent', color: 'blue', icon: ArrowRightLeft },
    ],
    columns: [
      { header: 'Month', accessorKey: 'month' },
      { header: 'POs Created', accessorKey: 'poCount', align: 'right' },
      { header: 'Total Value', accessorKey: 'totalValue', align: 'right', format: 'currency' },
      { header: 'MoM Change', accessorKey: 'momChange', align: 'right', format: 'percent' },
      { header: 'Top Supplier', accessorKey: 'topSupplier' },
    ],
  },
]
