import { CalendarDays, Table2, PhoneCall, Ban, Clock, MapPinned } from 'lucide-react'
import type { ReportConfig } from '../types/report-config.types'

export const reservationReports: ReportConfig[] = [
  {
    id: 'reservation-overview',
    title: 'Reservation Overview',
    description: 'All reservations by status with daily timeline',
    icon: CalendarDays,
    iconBg: 'bg-blue-600',
    category: 'reservation',
    categoryLabel: 'Reservations & Seating',
    endpoint: '/reports/reservation/overview',
    kpis: [
      { label: 'Total Today', dataKey: 'todayCount', format: 'number', color: 'blue', icon: CalendarDays },
      { label: 'Confirmed', dataKey: 'confirmed', format: 'number', color: 'emerald', icon: CalendarDays },
      { label: 'Seated', dataKey: 'seated', format: 'number', color: 'purple', icon: Table2 },
      { label: 'Cancelled', dataKey: 'cancelled', format: 'number', color: 'red', icon: Ban },
    ],
    columns: [
      { header: 'Guest', accessorKey: 'guestName' },
      { header: 'Date', accessorKey: 'scheduledFor', format: 'date' },
      { header: 'Party Size', accessorKey: 'partySize', align: 'right' },
      { header: 'Status', accessorKey: 'status' },
      { header: 'Source', accessorKey: 'source' },
      { header: 'Table', accessorKey: 'tableLabel' },
    ],
    searchable: true,
    searchFields: ['guestName', 'status', 'source', 'tableLabel'],
  },
  {
    id: 'table-utilization',
    title: 'Table Utilization Report',
    description: 'Occupancy rates, revenue, and table performance',
    icon: Table2,
    iconBg: 'bg-emerald-600',
    category: 'reservation',
    categoryLabel: 'Reservations & Seating',
    endpoint: '/reports/reservation/table-utilization',
    kpis: [
      { label: 'Avg Utilization', dataKey: 'avgUtilization', format: 'percent', color: 'emerald', icon: Table2 },
      { label: 'Rev per Seat', dataKey: 'revenuePerSeat', format: 'currency', color: 'blue', icon: Clock },
    ],
    columns: [
      { header: 'Table', accessorKey: 'tableLabel' },
      { header: 'Zone', accessorKey: 'zoneName' },
      { header: 'Capacity', accessorKey: 'capacity', align: 'right' },
      { header: 'Utilization', accessorKey: 'utilizationRate', align: 'right', format: 'percent' },
      { header: 'Revenue', accessorKey: 'revenue', align: 'right', format: 'currency' },
      { header: 'Avg Duration', accessorKey: 'avgDuration', align: 'right' },
    ],
    searchable: true,
    searchFields: ['tableLabel', 'zoneName'],
  },
  {
    id: 'reservation-source',
    title: 'Reservation Source Analysis',
    description: 'Booking channel effectiveness and conversion',
    icon: PhoneCall,
    iconBg: 'bg-purple-600',
    category: 'reservation',
    categoryLabel: 'Reservations & Seating',
    endpoint: '/reports/reservation/source',
    kpis: [
      { label: 'Online', dataKey: 'onlineCount', format: 'number', color: 'purple', icon: PhoneCall },
      { label: 'Phone', dataKey: 'phoneCount', format: 'number', color: 'blue', icon: PhoneCall },
      { label: 'Walk-in', dataKey: 'walkinCount', format: 'number', color: 'amber', icon: CalendarDays },
    ],
    columns: [
      { header: 'Source', accessorKey: 'source' },
      { header: 'Count', accessorKey: 'count', align: 'right' },
      { header: '% of Total', accessorKey: 'percentage', align: 'right', format: 'percent' },
      { header: 'Avg Party Size', accessorKey: 'avgPartySize', align: 'right', format: 'decimal' },
      { header: 'No-Show Rate', accessorKey: 'noShowRate', align: 'right', format: 'percent' },
    ],
  },
  {
    id: 'reservation-no-show',
    title: 'No-Show & Cancellation Report',
    description: 'Lost revenue from no-shows and cancellations',
    icon: Ban,
    iconBg: 'bg-red-600',
    category: 'reservation',
    categoryLabel: 'Reservations & Seating',
    endpoint: '/reports/reservation/no-show',
    kpis: [
      { label: 'No-Show Rate', dataKey: 'noShowRate', format: 'percent', color: 'red', icon: Ban },
      { label: 'Cancel Rate', dataKey: 'cancelRate', format: 'percent', color: 'amber', icon: Clock },
      { label: 'Lost Revenue Est.', dataKey: 'lostRevenue', format: 'currency', color: 'purple', icon: Clock },
    ],
    columns: [
      { header: 'Period', accessorKey: 'period' },
      { header: 'No-Shows', accessorKey: 'noShows', align: 'right' },
      { header: 'Cancellations', accessorKey: 'cancellations', align: 'right' },
      { header: 'No-Show Rate', accessorKey: 'noShowRate', align: 'right', format: 'percent' },
      { header: 'Cancel Rate', accessorKey: 'cancelRate', align: 'right', format: 'percent' },
    ],
  },
  {
    id: 'reservation-peak-hours',
    title: 'Peak Hours & Demand Forecasting',
    description: 'Hourly demand patterns and table availability',
    icon: Clock,
    iconBg: 'bg-indigo-600',
    category: 'reservation',
    categoryLabel: 'Reservations & Seating',
    endpoint: '/reports/reservation/peak-hours',
    kpis: [
      { label: 'Peak Hour Demand', dataKey: 'peakDemand', format: 'number', color: 'indigo', icon: Clock },
      { label: 'Avg Party Size', dataKey: 'avgPartySize', format: 'decimal', color: 'blue', icon: CalendarDays },
    ],
    columns: [
      { header: 'Hour', accessorKey: 'hour' },
      { header: 'Day', accessorKey: 'dayOfWeek' },
      { header: 'Reservations', accessorKey: 'reservationCount', align: 'right' },
      { header: 'Avg Party Size', accessorKey: 'avgPartySize', align: 'right', format: 'decimal' },
      { header: 'Demand Score', accessorKey: 'demandScore', align: 'right' },
    ],
  },
  {
    id: 'zone-performance',
    title: 'Zone Performance Report',
    description: 'Revenue and utilization by seating zone',
    icon: MapPinned,
    iconBg: 'bg-rose-600',
    category: 'reservation',
    categoryLabel: 'Reservations & Seating',
    endpoint: '/reports/reservation/zone-performance',
    kpis: [
      { label: 'Zones', dataKey: 'zoneCount', format: 'number', color: 'rose', icon: MapPinned },
      { label: 'Avg Utilization', dataKey: 'avgUtilization', format: 'percent', color: 'emerald', icon: Table2 },
    ],
    columns: [
      { header: 'Zone', accessorKey: 'zoneName' },
      { header: 'Tables', accessorKey: 'tableCount', align: 'right' },
      { header: 'Total Capacity', accessorKey: 'totalCapacity', align: 'right' },
      { header: 'Utilization', accessorKey: 'utilizationRate', align: 'right', format: 'percent' },
      { header: 'Revenue', accessorKey: 'revenue', align: 'right', format: 'currency' },
      { header: 'Rev/Seat', accessorKey: 'revenuePerSeat', align: 'right', format: 'currency' },
    ],
  },
]
